import { IPropsMapper } from '../../../types/generic';

export const SelectTheme: IPropsMapper<object> = {
  container: {
    position: 'relative',
    width: 'w-full',
    minWidth: 'min-w-[200px]',
  },
  select: {
    peer: 'peer',
    width: 'w-full',
    height: 'h-full',
    bg: 'bg-transparent',
    color: 'text-blue-gray-700',
    fontFamily: 'font-sans',
    fontWeight: 'font-normal',
    textAlign: 'text-left',
    outline: 'outline outline-0 focus:outline-0',
    disabled: 'disabled:bg-blue-gray-50 disabled:border-0',
    transition: 'transition-all',
    cursor: 'cursor-pointer',
  },
  arrow: {
    initial: {
      display: 'grid',
      placeItems: 'place-items-center',
      position: 'absolute',
      top: 'top-2/4',
      right: 'right-2',
      pt: 'pt-px',
      width: 'w-5',
      height: 'h-5',
      color: 'text-blue-gray-400',
      transform: 'rotate-0 -translate-y-2/4',
      transition: 'transition-all',
    },
    active: {
      transform: 'rotate-180',
      mt: 'mt-px',
    },
  },
  label: {
    display: 'flex',
    width: 'w-full',
    height: 'h-full',
    userSelect: 'select-none',
    pointerEvents: 'pointer-events-none',
    position: 'absolute',
    left: 'left-0',
    fontWeight: 'font-normal',
    transition: 'transition-all',
  },
  "option-container": {
    width: 'w-full',
    maxHeight: 'max-h-96',
    bg: 'bg-white',
    p: 'p-3',
    border: 'border border-blue-gray-50',
    borderRadius: 'rounded-md',
    boxShadow: 'shadow-lg shadow-blue-gray-500/10',
    fontFamily: 'font-sans',
    fontSize: 'text-sm',
    fontWeight: 'font-normal',
    color: 'text-blue-gray-500',
    overflow: 'overflow-auto',
    outline: 'focus:outline-none',
  },
  option: {
    initial: {
      width: 'w-full',
      pt: 'pt-[9px]',
      pb: 'pb-2',
      px: 'px-3',
      borderRadius: 'rounded-md',
      lightHeight: 'leading-tight',
      cursor: 'cursor-pointer',
      background: 'hover:bg-blue-gray-50 focus:bg-blue-gray-50',
      opacity: 'hover:bg-opacity-80 focus:bg-opacity-80',
      color: 'hover:text-blue-gray-900 focus:text-blue-gray-900',
      userSelect: 'select-none',
      outline: 'outline outline-0',
      transition: 'transition-all',
    },
    active: {
      bg: 'bg-blue-gray-50 bg-opacity-80',
      color: 'text-blue-gray-900',
    },
    disabled: {
      opacity: 'opacity-50',
      cursor: 'cursor-not-allowed',
      userSelect: 'select-none',
      pointerEvents: 'pointer-events-none',
    },
  },
};
